DefaultContentLanguage = "en"
baseurl = "https://sean-stanley.gitlab.io/homeopathica/"
canonifyurls = true
cloudinary_url = "https://res.cloudinary.com/maplekiwi/image/upload"
contentdir = "content"
layoutdir = "layouts"
metaDataFormat = "yaml"
publishdir = "public"
pygmentCodeFences = true
pygmentsUseClasses = true
theme = "universal-homeopathica"
title = "Homeopathica"
[Author]
bandcamp = "username"
email = "youremail@domain.com"
facebook = "username"
github = "username"
gitlab = "username"
googleplus = "+username"
instagram = "username"
itchio = "username"
keybase = "username"
linkedin = "username"
name = "Some Person"
reddit = "username"
snapchat = "username"
soundcloud = "username"
spotify = "username"
stackoverflow = "users/XXXXXXX/username"
twitter = "username"
xing = "username"
youtube = "user/username"
[Params]
about_us = "<p>Veronika Zhmurko, Registered Homeopath, PhD</p>"
cloudinary_url = "https://res.cloudinary.com/maplekiwi/image/upload"
comments = true
commit = false
copyright = "Copyright (c) 2005 - 2019, Homeopathcia; all rights reserved."
dateFormat = "January 2, 2006"
date_format = "January 2, 2006"
email = "vzhmurko@gmail.com"
favicon = "img/favicon.ico"
logo = "img/avatar-icon.png"
rss = true
style = "red"
subtitle = "Homeopathica"
[Params.carousel]
enable = true
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5
[[menu.main]]
name = "Credentials"
weight = 4
[[menu.main]]
name = "About Homeopathy"
url = "/about/"
weight = 3
[[menu.main]]
name = "Health Advice"
url = "/articles"
weight = 2
